### ISSUE TITLE
[Suggestion] Same kind of cool widget but for invite links?

### ISSUE THREAD

**Issue by couleurm** [Vendicated/DiscordWidgets#12]
hey cool repo, it'd be super cool to have something like this for invites that'd faithful to how it looks in-app

(that you could use can use on any website with a little bit of css/html/js)

![image](https://github.com/Vendicated/DiscordWidgets/assets/82747632/8577e329-097f-44a0-87ad-352ae82db15b)

**Comment by wont-stream** [comment]
Projects already exist for that, a notable one being https://github.com/SwitchbladeBot/invidget
