### ISSUE TITLE
User not found

### ISSUE THREAD

**Issue by retrozinndev** [Vendicated/DiscordWidgets#16]
Hello! I've been using this project on my website, but it stopped working today for some reason...
It was working very well since this happened, what's wrong with it?
Example:
![image](https://github.com/Vendicated/DiscordWidgets/assets/65513943/0ca76cf1-6789-428d-b585-f0a0ffb8d7d7)

This happens in the [widgets page](https://widgets.vendicated.dev/) too:
![image](https://github.com/Vendicated/DiscordWidgets/assets/65513943/c36371a5-70fb-4d19-890b-2117bea39e5f)

**Comment by Vendicated** [comment]
~~Discord made it so you can no longer fetch users with whom your bot shares no mutual server. This means, you need to join this server for the widget to work with your user id: https://discord.gg/9HpMZv4NeR~~

~~See https://github.com/discord/discord-api-docs/issues/6876~~

**Comment by Vendicated** [comment]
Discord is reverting this change, so this will be fixed soon

**Comment by retrozinndev** [comment]
Thanks for the information!

**Comment by Vendicated** [comment]
made cards display a prominent explanation for now because this is still taking a while to be fixed. Discord's deploy is slooow...

![image](https://github.com/Vendicated/DiscordWidgets/assets/45497981/3a946e5e-1324-4bee-a2c4-1d19a0f5c6dc)

**Comment by retrozinndev** [comment]
Just got fixed, it's working now!
![image](https://github.com/Vendicated/DiscordWidgets/assets/65513943/137d94f8-737a-4fa6-b042-4853848d51c4)
Thanks for the help!

**Comment by FR4CS** [comment]
There is a bug again

**Comment by retrozinndev** [comment]
> There is a bug again

It's working for me
