### ISSUE TITLE
Add a variable for custom theme color

### ISSUE THREAD

**Issue by vorlie** [Vendicated/DiscordWidgets#3]
If someone does have different website design and they want to change the theme color to match their page/site, but they can't so they might fork the repo and change it manually. (As I did) I think that's a good idea tho

**Comment by Vendicated** [comment]
I agree!

**Comment by Vendicated** [comment]
PRs always welcome if you wanna add this

**Comment by Vendicated** [comment]
Added in https://github.com/Vendicated/DiscordWidgets/commit/e93274fcd3b692396a948f3689d6cb10e2c1a476
