### ISSUE TITLE
Ability to display activities

### ISSUE THREAD

**Issue by IvanGodinez21** [Vendicated/DiscordWidgets#4]
I would really like to see my activity been shown in the widget. I'm not sure if that is possible, but reading the OAuth2, I've seen this option. Obviously, it will require to create a [Discord Application](https://discord.com/developers/applications) for that.

![Discord-OAuth2-permissions](https://github.com/Vendicated/DiscordWidgets/assets/45635827/1808cc14-7353-4522-8646-d4dfcedeec36)

**Comment by Vendicated** [comment]
you can't actually use that oauth scope. if you want to show your activity, there are other projects like [lanyard](https://github.com/Phineas/lanyard)

**Comment by IvanGodinez21** [comment]
> you can't actually use that oauth scope. if you want to show your activity, there are other projects like [lanyard](https://github.com/Phineas/lanyard)

I understand, thanks for the info 👌
